### ISSUE TITLE
Minifies image breaking semantics

### ISSUE THREAD

**Issue by asm0dey** [orisano/minid#1]
if we build image from following Dockerfile:

```Dockerfile
FROM bash

ENV A=3
ENV B=$A
```
and run `echo $B` inside it we get `3` in output

When we're minifying this image using minid, we're getting following minified Dockerfile:

```Dockerfile
FROM bash
ENV A=3 B=$A
```

When we run `echo $B` inside it we're getting empty string which is semantically incorrect.
Please fix

**Comment by orisano** [comment]
Thanks for your reporting.
Maybe fixed on e5095a628cde357fe861fa154937e75294271782
